### ISSUE TITLE
Package binaries or build step documentation

### ISSUE THREAD

**Issue by noam-c** [libRocket/libRocket#218]
I'm aware that 1.3.0 is tagged as a "pseudo" release, but it would be nice if the dev and runtime binaries were packaged for use with that release (or a more recent one if it's coming soon).
Right now, when a project takes a dependency on libRocket, the project developers need to build libRocket from source on their respective platforms. For someone new to building libRocket, the process looks something like this on Windows 8 with Visual Studio 12:
1. Download libRocket source (or clone using GitHub app).
2. In the shell of your choice, find the CMakeLists.txt (it's in Build) and run cmake.
3. Oh, looks like it has a Freetype dependency. Let's go to http://www.freetype.org/download.html and find the binaries we need.
4. Alright, binaries unpacked and put in my Visual Studio "VC" folder.
5. Oh, CMake still can't find it. Let's read FindFreetype.cmake and see what happened.
6. Hm, it doesn't include VC/lib/freetype2 and VC/include/freetype2. Let's run CMake Config to set those paths, or set a FREETYPE_DIR environment variable.
7. Alright! Now CMake works and produces libRocket.sln for VS2013. Hit "Build Solution" and away we go!
8. ...or not. Why do I have so many build errors? What does "error LNK2026: module unsafe for SAFESEH image" mean and why does it appear 10 times in a row?
9. According to StackOverflow (here: http://stackoverflow.com/questions/10599940/module-unsafe-for-safeseh-image-c), the Windows binary that I just downloaded for Freetype2 is out of date. Lo and behold, it's 2.4.2, while the latest version is actually 2.5.3. Guess now I need to build Freetype from source too...

...and so on.

Other libraries I depend on simply require that I download lib and include files and extract them someplace that CMake can find them. By comparison, I end up spending an order of magnitude longer getting libRocket set up on my machines (OS X and Windows 8). There are no binaries, and I can't actually find much documentation on the process (in fact, the only documentation assumes that you've already got binaries: http://librocket.com/wiki/documentation/C%2B%2BManual/GettingStarted). I'm patient enough to do this for my own project, but it's hard to convince other developers to volunteer on my project if the process looks like the one above just for one of my project's dependencies.

To demonstrate that this isn't a Windows-specific problem: Issue #90 produced a cryptic error that could have been avoided by knowing how to properly build Freetype on OS X, or by having the binaries available as a download on GitHub.

I appreciate that packaging these binaries for a series of platforms (and, in the process, determining which platforms do and don't get binary packages) isn't easy or quick. If supplying binaries is not feasible, then a list of steps would still save a lot of time, as new developers on libRocket-dependent projects could just read those instructions instead of learning the hard way how to get the binaries they need on each of their environments.

**Comment by statico** [comment]
My apologies for piling onto this thread, but I'll add my experience here for Mac OS X 10.10.2 in case anyone else is stumped and finds this issue:

1. The Homebrew package for Boost was sufficient:
   1. `brew install boost`
   1. (I probably had some other dependencies already installed, YMMV)
1. I had to build freetype-2.5.5 with multiple architectures (the samples want i386):
   1. `./configure CFLAGS='-arch i386 -arch x86_64' CXXFLAGS='-arch i386 -arch x86_64' --without-png --prefix=/tmp/freetype`
   1. `make -j8 && make install`
1. Then I built libRocket:
   1. `ccmake . -DFREETYPE_LIBRARY=/tmp/freetype/lib/libfreetype.dylib -DFREETYPE_INCLUDE_DIRS=/tmp/freetype/include`
   1. <kbd>c</kbd> to configure, set `BUILD_SAMPLES` to `ON`, <kbd>c</kbd> to configure again, <kbd>g</kbd> to generate the Makefile
   1. `make -j8`
1. Then I could run the samples, but the working directory has to be correct. For example:
   1. `cd ../Samples/invaders`
   1. `../../Build/invaders.app/Contents/MacOS/invaders`

Success!
