### ISSUE TITLE
sample invaders issue

### ISSUE THREAD

**Issue by consultit** [libRocket/libRocket#263]
I just built the latest source from git (on linux debian), but when running the invaders sample  the select input, in the start_game.rml document, is black preventing selection from being seen.
I tried to tweak invader.rcss style sheet with no luck.

![select-input-issue](https://cloud.githubusercontent.com/assets/3671110/8637782/b3dc13cc-28a3-11e5-9bc1-276411795c17.png)

**Comment by dwimsey** [comment]
Hrm, that's definitely not right, I'll have a look at it when I get back home next week.  I may need more info about your setup to trouble shoot it if you don't mind.

**Comment by consultit** [comment]
My mistake: there was some some remainings of an old installation that interfered. I cleaned all and all works fine.
Sorry

**Comment by consultit** [comment]
I build on debian 8 (jessie) using cmake.
By trying some previous commit I discovered that  latest commit that works correctly is ce7240e5 on 2015-04-26 and a next commit (f93e90be on 2015-06-10, author flamingo) introduced this issue.
Using 'git diff f93e90be ce7240e5'  this issue seems related to Source/Core/DecoratorTiled.cpp modifications.
(I checked this results carefully so to avoid mistakes).

```
diff --git a/Source/Core/DecoratorTiled.cpp b/Source/Core/DecoratorTiled.cpp
index 22c84dc..a207cc7 100644
--- a/Source/Core/DecoratorTiled.cpp
+++ b/Source/Core/DecoratorTiled.cpp
@@ -108,11 +108,6 @@ Vector2f DecoratorTiled::Tile::GetDimensions(Element* element)
 void DecoratorTiled::Tile::GenerateGeometry(std::vector< Vertex >& vertices, std::vector< int >& indices, Element* element, const Vector2f& surface_origin, const Vector2f& surface_dimensions, const Vector2f& tile_dimensions) const
 {
        RenderInterface* render_interface = element->GetRenderInterface();
-       const Property* element_colour = element->GetProperty(COLOR);
-       Colourb quad_colour = Colourb(255, 255, 255);
-       if (element_colour)
-               quad_colour = element_colour->Get<Colourb>();
-       
        TileDataMap::iterator data_iterator = data.find(render_interface);
        if (data_iterator == data.end())
                return;
@@ -249,7 +244,7 @@ void DecoratorTiled::Tile::GenerateGeometry(std::vector< Vertex >& vertices, std
                        tile_position.x = surface_origin.x + (float) tile_dimensions.x * x;
                        tile_size.x = (float) (x < num_tiles[0] - 1 ? tile_dimensions.x : final_tile_dimensions.x);
 
-                       GeometryUtilities::GenerateQuad(new_vertices, new_indices, tile_position, tile_size, quad_colour, tile_texcoords[0], tile_texcoords[1], index_offset);
+                       GeometryUtilities::GenerateQuad(new_vertices, new_indices, tile_position, tile_size, Colourb(255, 255, 255), tile_texcoords[0], tile_texcoords[1], index_offset);
                        new_vertices += 4;
                        new_indices += 6;
                        index_offset += 4;
```

**Comment by consultit** [comment]
As an update: I just forked master branch, reverted Source/Core/DecoratorTiled.cpp changes and this issue is no longer there.

**Comment by dwimsey** [comment]
Tracked this down to a RCSS issue for the SELECT element which forces them to black.  Have to do some more digging for the proper fix to the RCSS to get this one to go away.  The code appears to be functioning correctly.
