### ISSUE TITLE
Wrong use of ROCKET_UNUSED in FontParser

### ISSUE THREAD

**Issue by OgreTransporter** [libRocket/libRocket#268]
Bug in commit https://github.com/libRocket/libRocket/commit/cbbbed70a85f5b51cea62d75cc13c0fd88150c7a (PR https://github.com/libRocket/libRocket/pull/267 ):

Macro ROCKET_UNUSED is not allowed in function Header. Also, the macro result (UNSUSED_name, UNUSED_data) is not defined.

**Comment by OgreTransporter** [comment]
Fix: PR https://github.com/libRocket/libRocket/pull/269

**Comment by dwimsey** [comment]
Fixed in PR 270
